### PR TITLE
add license title

### PR DESCRIPTION
**Pull request by waldyrious**
It's not strictly required, but it's useful metadata, and part of the recommended license template text (see http://choosealicense.com/licenses/isc/ and https://opensource.org/licenses/isc-license)

### CODE REVIEW

**Comment by meyerweb** [comment]
Yep, good catch.  Merged.  Thanks, waldyrious!

**Comment by waldyrious** [comment]
No problem :) thanks for the quick merge!

**Comment by waldyrious** [comment]
@meyerweb would you like me to send similar PRs to your other repos, or do you prefer to edit their license files directly yourself? It's not a problem for me, I'm just asking because I don't want to be a nuisance and "spam" you :)

**Comment by meyerweb** [comment]
Sure, go for it.  Thanks!

**Comment by waldyrious** [comment]
@meyerweb done :)

**Pull request merged**
