### PR TITLE
Feature modern library

### PR DESCRIPTION
**Pull request by nyamsprod**
I needed to incorporate this work into a modern application using composer.  So what I basically did was:
- use namespace
- add unit testing
- used PHP-FIG standard (PSR-2 and PSR-4) 
- added two complementary methods saveSVG and toXML to be able to directly save the SVG into a file or to manipulate it further.
- the composer.json states that it needs at least PHP 5.4

I've also updated the README.md file to show how to use the converter class

### CODE REVIEW

**Comment by meyerweb** [comment]
So this is a LOT of change, and I’m not clear on everything that happened.  Is this basically just converting everything to Composer, without really changing the core code?  Or were there also changes in how the converter actually does its thing?

**Comment by nyamsprod** [comment]
Well apart from making the code composer ready, I've updated the core code to create the SVG not with strings but with PHP DOMDocument. That's way the final SVG can directly be saved to a file or exported as a DOMDocument object for further manipulation.

**Comment by meyerweb** [comment]
Okay, I think I get it.  This is…a very significant change.  I need to figure out how to pull as a branch I can test out before I can decide whether to merge.  Or, if you have a copy available for easy download, let me know and I'll grab it.  Thanks!

**Comment by nyamsprod** [comment]
if you want I can make a pull request against another branch in your repo ?

**Comment by nyamsprod** [comment]
Since I didn't know how to do It I've made this quick packagist library. I'll remove it if you are okay to merge the changes back to your library I don't feel like maintaining to library for that is really useful :+1:
https://packagist.org/packages/bakame/pixels2svg

**Comment by meyerweb** [comment]
Eh, what the hell.  Approved.  Thanks!

**Comment by meyerweb** [comment]
I’ve been struggling to fix the errors that this update apparently introduced.  Basically, only vertical runs work as intended; horizontal runs are mangled in ways that don’t make sense to me.  See the examples in the test directory.  If you can find the error and fix it, please do so.  Otherwise I’m going to have to roll everything back to the last point at which the code seemed to (mostly) work, which was before all the Composer refactoring.

**Comment by meyerweb** [comment]
Followup: I’ve traced the problem to the threshold routine(s).  It’s present in the pre-Composer codebase, but not as pronounced.  That is, if you set the threshold to 0, images are converted without distortion.  Anything above that will distort several of the images.  In the pre-Composer codebase, only the Darth Vader image is affected by raising the threshold above 0; all others seem fine.  (Note: I did not test for all possible threshold values.)

**Comment by meyerweb** [comment]
Okay, so, I had a breakthrough of sorts.  The looping for horizontal runs was broken by dint of not really being done at all.  I updated `generateSvgFromRaster()` to loop properly in the two cases, which fixed most of the problem.

Separately, the `checkThreshold()` code was causing problems, so I removed that check.  The threshold-related code is still in the PHP, just not called when doing color comparisons.  I’ll open a separate issue on that.  Sorry to have cluttered up your activity feed with this!

**Comment by nyamsprod** [comment]
@meyerweb You did not on the contrary... I did not notice this bug and it seems you resolve it.

**Pull request merged**
